[package]
name = "fields"
version.workspace = true
edition.workspace = true

[dependencies]
once_cell = "^1"
fields-derive = { path = "../fields-derive" }
chrono = { version = "^0.4", optional = true }

[features]
default = []
chrono = ["dep:chrono"]
