[package]
name = "fields-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "^2"
quote = "^1"
proc-macro2 = "^1"
proc-macro-error = "^1"

[dev-dependencies]
fields = { path = "../fields" }
